services:

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgresnet
  
  migration:
    build:
      context: .
      target: migration
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/example
    networks:
      - postgresnet

  server:
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/example
    networks:
      - postgresnet

volumes:
  db-data: 

secrets:
  db-password:
    file: db/password.txt

networks:
  postgresnet: